update workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,13 +62,23 @@ jobs:
           docker stop world
           docker rm world
           docker image rm database
+      - name: Build and Run Tests
+        run: mvn clean install
+
+      - name: Verify JaCoCo Report
+        run: |
+          if [ ! -f ./target/site/jacoco/jacoco.xml ]; then
+            echo "JaCoCo report not found!"
+            exit 1
+          fi
+
       - name: CodeCov
         uses: codecov/codecov-action@v2
         with:
           token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-          directory: ./target/site/jacoco/jacoco.xml
-          flags: Integration Tests # optional
-          verbose: true # optional (default = false)
+          file: ./target/site/jacoco/jacoco.xml
+          flags: Integration Tests
+          verbose: true
   build:
     name: Build and Start Using docker compose
     runs-on: ubuntu-20.04
